### ISSUE TITLE
Can't find variable: DS

### ISSUE THREAD

**Issue by A5308H** [WMeldon/ember-cli-todos#5]
Don't know what I'm doing wrong.
I executed the following commands:
1. git clone https://github.com/WMeldon/ember-cli-todos
2. cd ember-cli-todos
3. npm install
4. bower install (although I think npm install already called this)
5 .ember test

>> I get 10 failures: "Can't find variable: DS"

**Comment by stefanpenner** [comment]
this repo has gotten quite out of date

**Comment by stefanpenner** [comment]
i will update it this morning, just got most of it updated. Gotta fix some deprecations yet

**Comment by A5308H** [comment]
Wow! That was quick! Thank you. And thanks for hosting this example at all :+1:

**Comment by stefanpenner** [comment]
@A5308H the branch should be working now, going to merge once travis is green.

planning to update it to be more idiomatic shortly

**Comment by A5308H** [comment]
Yes. It's working on my machine now. Thanks for the quick reaction again!

**Comment by stefanpenner** [comment]
@A5308H no problem, I plan to keep it more up to date going forward.
