### ISSUE TITLE
Wrong scoping of item count

### ISSUE THREAD

**Issue by felixbuenemann** [WMeldon/ember-cli-todos#9]
The "n items left" counter is not scoped properly. When on the completed state, it will always shows zero instead of the actual number of remaining items.

**Comment by stefanpenner** [comment]
fixed on new org: https://github.com/ember-cli/ember-cli-todos

**Comment by felixbuenemann** [comment]
Thanks, Stefan!

**Comment by stefanpenner** [comment]
kein problem
